#!/bin/sh

version=$(< src/main/resources/application.yml grep version: | awk -F ': ' '{print $2}')
echo "Current version: $version, writing to pom.xml."
xmlstarlet ed --inplace -N N="http://maven.apache.org/POM/4.0.0" -u '//N:project/N:version' -v "$version" pom.xml
